=== Patonito/ASIR-Lengua/Unit3/LAB 2. UNITS 2 & 3/smsDB.dtd
<!ELEMENT smsDB (sms)*>
<!ELEMENT sms (phone, date, time, message, spam)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT message(#PCDATA)>
<!ELEMENT spam EMPTY>

=== Patonito/ASIR-Lengua/Unit3/LAB 2. UNITS 2 & 3/dtd_4.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE smsDB SYSTEM "smsDB.dtd">
<smsDB>
    <sms>
    <phone>955 55 76 55</phone>
    <date>1/7/2011</date>
    <time>23:55</time>
    <message>Hi, are we meeting at 10:00?</message>
 </sms>
    <sms>
    <phone>745 1536 11</phone>
    <date>22/9/2011</date>
    <time>15:05</time>
    <message>Download Arkanoid from http://download.arcanoid.com/win</message>
    <spam/>
 </sms>
 <sms>
    <phone>842 35 11 00</phone>
    <date>10/11/2011</date>
    <time>09:22</time>
    <message>Thank you for the information, regards</message>
    </sms>
</smsDB>
